### ISSUE TITLE
votemap for other gamemode

### ISSUE THREAD

**Issue by MarcoDz** [clrksml/jailbreak#1]
Hey,

Nice gamemode and all ui are beautiful , but like the title say i want to use the votemap whit other gamemode like prophunt or zombie survival could it be possiby ?

thanks for reading

**Comment by clrksml** [comment]
It could be. However all the images I manually captured so somebody would have to do that. Sorry for the late response github didn't email me that their was an open issue.

I did make a votemap addon back  in 2013. It pretty much the same thing. https://drive.google.com/file/d/1_0cTGWRLZS92f34Q2YeYW8PjGgMTQ1tv/view?usp=drivesdk

**Comment by MarcoDz** [comment]
Nice,

Thanks a alot and nice gamemode good keep it up!!
